version: 2

models:
  - name: stg_orders
    description: "Staging model for Olist orders (filtered and renamed)"
    columns:
      - name: order_id
        description: "Unique identifier of an order"
        tests:
          - not_null
          - unique
          - relationships:
              to: ref('stg_orders_raw')
              field: order_id
      - name: customer_id
        description: "Customer associated with the order"
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id

      - name: order_status
        description: "Current status of the order"
        tests:
          - not_null
  - name: stg_order_items
    description: "Staging model for order items (one row per order item)"
    columns:
      - name: order_id
        description: "Order identifier"
        tests:
          - not_null
          - relationships:
              to: ref('stg_orders_raw')
              field: order_id

      - name: order_item_id
        description: "Item number within the order"
        tests:
          - not_null

      - name: seller_id
        description: "Seller responsible for the item"
        tests:
          - not_null
          - relationships:
              to: ref('stg_sellers')
              field: seller_id
  - name: stg_reviews
    description: >
      Staging model for raw order reviews (may contain duplicates per order).
      Raw customer reviews.
      Multiple rows per order_id and review_id may exist due to review updates.
    columns:
      - name: order_id
        description: "Order identifier associated with the review"
        tests:
          - not_null
          - relationships:
              to: ref('stg_orders_raw')
              field: order_id

      - name: review_id
        description: "Unique identifier of the review"
        tests:
          - not_null

      - name: review_score
        description: "Customer satisfaction score (5)"
        tests:
          - not_null
  - name: stg_customers
    description: "Staging model for Olist customers"
    columns:
      - name: customer_id
        description: "Unique identifier of a customer"
        tests:
          - not_null
          - unique            
      - name: customer_unique_id
        description: "Unique identifier for a customer across multiple orders"
        tests:
          - not_null
      - name: customer_zip_code_prefix
        description: "Zip code prefix of the customer"
        tests:
          - not_null
      - name: customer_city
        description: "City of the customer"
        tests:
          - not_null
      - name: customer_state
        description: "State of the customer"
        tests:
          - not_null
  - name: stg_sellers
    description: "Staging model for Olist sellers"
    columns:
      - name: seller_id
        description: "Unique identifier of a seller"      
        tests:
          - not_null
          - unique
      - name: seller_zip_code_prefix
        description: "Zip code prefix of the seller"
        tests:
          - not_null
      - name: seller_city
        description: "City of the seller"
        tests:
          - not_null
      - name: seller_state
        description: "State of the seller"  
  - name: stg_orders_raw
    description: "Raw staging model for Olist orders (no filtering)"
    columns:
      - name: order_id
        description: "Unique identifier of an order"
        tests:
          - not_null
          - unique
      - name: customer_id
        description: "Customer associated with the order"
        tests:
          - not_null
      - name: order_status
        description: "Current status of the order"
        tests:
          - not_null
      - name: order_purchase_timestamp
        description: "Timestamp when the order was purchased"
      - name: delivered_date
        description: "Timestamp when the order was delivered to the customer"
      - name: estimated_delivery_date
        description: "Estimated delivery date for the order"    